name: Check for obs-studio Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/obsproject/obs-studio/releases/latest | jq -r .tag_name)
          echo "::set-output name=latest_release::$latest_release"

      - name: Check if new release
        id: check_release
        run: |
          echo "Latest release is ${{ steps.get_release.outputs.latest_release }}"
          if [ "${{ steps.get_release.outputs.latest_release }}" != "$(cat .latest_release)" ]; then
            echo "New release found"
            echo "::set-output name=new_release::true"
          else
            echo "No new release"
            echo "::set-output name=new_release::false"
          fi

      - name: Save latest release
        if: steps.check_release.outputs.new_release == 'true'
        run: echo "${{ steps.get_release.outputs.latest_release }}" > .latest_release

      - name: Trigger build-obs workflow
        if: steps.check_release.outputs.new_release == 'true'
        uses: actions/github-script@v4
        with:
          script: |
            latest_release=$(cat .latest_release)
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release-obs.yml',
              ref: context.ref,
              inputs: {
                obs_version: latest_release
              }
            })