name: Check for obs-studio Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache latest release
        id: cache_latest_release
        uses: actions/cache@v3
        with:
          path: .latest_release
          key: latest-release

      - name: Get latest release
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/obsproject/obs-studio/releases/latest | jq -r .tag_name)
          echo "latest_release=$latest_release" >> $GITHUB_ENV

      - name: Check if new release
        id: check_release
        run: |
          echo "Latest release is ${{ env.latest_release }}"
          if [ -f .latest_release ] && [ "${{ env.latest_release }}" != "$(cat .latest_release)" ]; then
            echo "New release found"
            echo "new_release=true" >> $GITHUB_ENV
          elif [ ! -f .latest_release ]; then
            echo "First run, creating release file"
            echo "new_release=true" >> $GITHUB_ENV
          else
            echo "No new release"
            echo "new_release=false" >> $GITHUB_ENV
          fi

      - name: Save latest release
        if: env.new_release == 'true'
        run: echo "${{ env.latest_release }}" > .latest_release

      - name: Trigger build-obs workflow
        if: env.new_release == 'true'
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DISPATCH_KEY }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/release-obs.yml/dispatches \
          -d '{"ref": "${{ github.ref_name }}", "inputs": {"obs_version":"${{ env.latest_release }}"}}'

      - name: Update cache
        if: env.new_release == 'true'
        uses: actions/cache@v3
        with:
          path: .latest_release
          key: latest-release
