name: Check for obs-studio Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/obsproject/obs-studio/releases/latest | jq -r .tag_name)
          echo "latest_release=$latest_release" >> $GITHUB_ENV

      - name: Check if new release
        id: check_release
        run: |
          echo "Latest release is ${{ env.latest_release }}"
          if [ "${{ env.latest_release }}" != "$(cat .latest_release)" ]; then
            echo "New release found"
            echo "new_release=true" >> $GITHUB_ENV
          else
            echo "No new release"
            echo "new_release=false" >> $GITHUB_ENV
          fi

      - name: Save latest release
        if: env.new_release == 'true'
        run: echo "${{ env.latest_release }}" > .latest_release

      - name: Trigger build-obs workflow
        if: env.new_release == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const latest_release = require("fs").readFileSync(".latest_release", "utf8").trim();
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release-obs.yml',
              ref: context.ref,
              inputs: {
                obs_version: latest_release
              }
            })
